{
    "type": "bundle",
    "id": "bundle--3ed5c083-c4c9-4330-8bfb-34308c0222f9",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--d80a3ae0-eec2-4c22-bbc7-e136c7b8c8d5",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-04-17T00:21:24.728846Z",
            "modified": "2025-04-17T00:21:24.728846Z",
            "name": "CVE-2025-3730",
            "description": "A vulnerability, which was classified as problematic, was found in PyTorch 2.6.0. Affected is the function torch.nn.functional.ctc_loss of the file aten/src/ATen/native/LossCTC.cpp. The manipulation leads to denial of service. An attack has to be approached locally. The exploit has been disclosed to the public and may be used. The name of the patch is 46fc5d8e360127361211cb237d5f9eef0223e567. It is recommended to apply a patch to fix this issue.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2025-3730"
                }
            ]
        }
    ]
}