{
    "type": "bundle",
    "id": "bundle--3d4595d3-e987-4140-a268-56b2dcd445e9",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--937998c9-eec6-46ad-af64-28e0f0c02540",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-11-26T00:21:07.413953Z",
            "modified": "2024-11-26T00:21:07.413953Z",
            "name": "CVE-2020-11311",
            "description": "This record is rejected as duplicate. All references should point to CVE-2021-1904.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2020-11311"
                }
            ]
        }
    ]
}